name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Validate configuration
      run: npm run validate
      
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## 🎉 New Release ${{ github.ref }}
          
          ### ✅ What's New
          - Automated release from tag ${{ github.ref }}
          - All tests passed
          - Configuration validated
          
          ### 📋 Changes
          See [CHANGELOG.md](CHANGELOG.md) for detailed changes.
          
          ### 🚀 Quick Start
          ```bash
          git clone https://github.com/${{ github.repository }}.git
          cd gas-boilerplate
          npm install
          npm test
          ```
          
          ### 📚 Documentation
          - [README.md](README.md) - Setup guide
          - [CURSOR_RULES.md](CURSOR_RULES.md) - AI assistant rules
          - [docs/](docs/) - Technical documentation
          
        draft: false
        prerelease: false
